# Generated by Django 4.2.2 on 2023-08-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='Email',
            field=models.EmailField(default='admin@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='members',
            name='MemberType',
            field=models.CharField(choices=[('1', 'New'), ('2', 'Silver'), ('3', 'Gold'), ('4', 'Diamond')], default='1', max_length=12),
        ),
        migrations.AlterModelTable(
            name='members',
            table='Members',
        ),
    ]
