# Generated by Django 4.2.2 on 2023-08-26 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_drinks_drinkscategory_delete_members_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinks',
            old_name='prince',
            new_name='price',
        ),
    ]
